import re
import pandas as pd


VALID_TYPES = {
    "task",
    "request",
    "deadline",
    "decision",
    "information",
    "none",
}

VALID_PRIORITIES = {
    "low",
    "medium",
    "high",
}


# --------------------------------------------------
# Helper: clean empty values
# --------------------------------------------------

def _clean_value(value):
    if (
        pd.isna(value)
        or str(value).strip().lower()
        in {"", "none", "null", "nan"}
    ):
        return None

    return str(value).strip()


# --------------------------------------------------
# Helper: get surrounding context
# --------------------------------------------------

def _get_context_text(df, message_id, window=2):

    matching_rows = df.index[
        df["message_id"] == message_id
    ].tolist()

    if not matching_rows:
        return ""

    current_index = matching_rows[0]

    start_index = max(
        0,
        current_index - window
    )

    end_index = min(
        len(df),
        current_index + window + 1
    )

    context_df = df.iloc[
        start_index:end_index
    ]

    context_lines = []

    for _, row in context_df.iterrows():

        context_lines.append(
            f'{row["user"]}: {row["message"]}'
        )

    return "\n".join(context_lines)


# --------------------------------------------------
# Helper: evidence validation
# --------------------------------------------------

def _evidence_exists_in_context(evidence, context):

    if not evidence or not context:
        return False

    evidence = str(evidence).strip().lower()
    context = str(context).strip().lower()

    if not evidence:
        return False

    # Direct evidence match
    if evidence in context:
        return True

    # Normalize whitespace
    normalized_evidence = re.sub(
        r"\s+",
        " ",
        evidence
    )

    normalized_context = re.sub(
        r"\s+",
        " ",
        context
    )

    return normalized_evidence in normalized_context


# --------------------------------------------------
# Main validation function
# --------------------------------------------------

def validate_ai_results(results, df):
    """
    Validate and clean AI-generated conversation results.

    Evidence generated by Gemini must exist in the
    original conversation context.

    No API calls are made here.
    """

    if results is None or results.empty:
        return pd.DataFrame()

    cleaned = results.copy()

    # --------------------------------------------------
    # 1. Validate message IDs
    # --------------------------------------------------

    valid_message_ids = set(
        df["message_id"].astype(int)
    )

    cleaned["message_id"] = pd.to_numeric(
        cleaned["message_id"],
        errors="coerce"
    )

    cleaned = cleaned[
        cleaned["message_id"].notna()
    ].copy()

    cleaned["message_id"] = (
        cleaned["message_id"]
        .astype(int)
    )

    cleaned = cleaned[
        cleaned["message_id"].isin(
            valid_message_ids
        )
    ].copy()

    # --------------------------------------------------
    # 2. Validate type
    # --------------------------------------------------

    cleaned["type"] = (
        cleaned["type"]
        .astype(str)
        .str.lower()
        .str.strip()
    )

    cleaned.loc[
        ~cleaned["type"].isin(VALID_TYPES),
        "type"
    ] = "none"

    # --------------------------------------------------
    # 3. Validate priority
    # --------------------------------------------------

    cleaned["priority"] = (
        cleaned["priority"]
        .astype(str)
        .str.lower()
        .str.strip()
    )

    cleaned.loc[
        ~cleaned["priority"].isin(
            VALID_PRIORITIES
        ),
        "priority"
    ] = "low"

    # --------------------------------------------------
    # 4. Clean task, deadline, evidence
    # --------------------------------------------------

    for column in [
        "task",
        "deadline",
        "evidence"
    ]:

        if column in cleaned.columns:

            cleaned[column] = (
                cleaned[column]
                .apply(_clean_value)
            )

        else:

            cleaned[column] = None

    # --------------------------------------------------
    # 5. Validate confidence
    # --------------------------------------------------

    cleaned["confidence"] = pd.to_numeric(
        cleaned["confidence"],
        errors="coerce"
    )

    cleaned["confidence"] = (
        cleaned["confidence"]
        .fillna(0.0)
        .clip(0.0, 1.0)
    )

    # --------------------------------------------------
    # 6. Normalize importance
    # --------------------------------------------------

    cleaned["is_important"] = (
        cleaned["is_important"]
        .astype(bool)
    )

    # --------------------------------------------------
    # 7. Validate evidence
    # --------------------------------------------------

    for index, row in cleaned.iterrows():

        message_id = int(
            row["message_id"]
        )

        context = _get_context_text(
            df,
            message_id,
            window=2
        )

        evidence = row["evidence"]

        # If AI claims something important but
        # provides no evidence, downgrade it.
        if (
            row["type"] != "none"
            and evidence is None
        ):

            cleaned.at[index, "type"] = "none"
            cleaned.at[index, "task"] = None
            cleaned.at[index, "deadline"] = None
            cleaned.at[index, "is_important"] = False

            continue

        # Evidence must actually exist in
        # the original conversation.
        if evidence is not None:

            if not _evidence_exists_in_context(
                evidence,
                context
            ):

                cleaned.at[index, "type"] = "none"
                cleaned.at[index, "task"] = None
                cleaned.at[index, "deadline"] = None
                cleaned.at[index, "is_important"] = False
                cleaned.at[index, "evidence"] = None

    # --------------------------------------------------
    # 8. Remove duplicate message IDs
    # --------------------------------------------------

    cleaned = cleaned.drop_duplicates(
        subset=["message_id"],
        keep="first"
    )

    # --------------------------------------------------
    # 9. Sort chronologically
    # --------------------------------------------------

    cleaned["date"] = pd.to_datetime(
        cleaned["date"],
        errors="coerce"
    )

    cleaned = (
        cleaned
        .sort_values("date")
        .reset_index(drop=True)
    )

    return cleaned